resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
# - name: controller
#   newName: ghcr.io/mborodin/uyuni-operator
#   newTag: dev
- name: controller
  newName: fayazlinux/uyuni-operator        # ← CHANGE THIS
  newTag: v1.0.0                            # ← CHANGE THIS (was: dev)