apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dockerhub-secret
    namespace: uyuni-operator-system
spec:
    secretTemplates:
        - name: dockerhub-secret
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:Pnq0uyRDI73m1GnDvAboV9hXtlcDJJK/fKw2CH0kkF/rdRaFGk2Jk7VvL3zBnCLT9TxL3v5iSWMqRys+D0tpLDsgZzPjm94kZPsMj9SF3n2bKtlUEORutWZTG2x/tV7zToQHF/HWhhNcdxHzjl1cUEgXBh7MMBnEQXFjYz45audNa2OfamRRQ2rxzFT/q0RS4/RuBlwkK/EPZ0D//kHrL1OQbyBrDnpu1ejDD79ztaME93FOG5rHk2y0/BiB6imz9MpGRUwvNNug0Kb4VVwfd78ec2OK1S7+pqAuuEe7PCAcZ2Ll0WJkD1lEF+D9KLWz7w/T5VM8oBHyVWde/Ufu5g==,iv:/IRMSG78Vj0yS0xvA4az3pqO71NJ7FfJw9HT4ese1iI=,tag:UMyGfvZN3bAb/2TLYdmSDg==,type:str]
sops:
    azure_kv:
        - vault_url: https://kv-becse-ngpdwe0150.vault.azure.net
          name: sops-key
          version: b9f8c5318f69463d9dece1f310af530b
          created_at: "2026-06-19T12:04:47Z"
          enc: X5tzpH1_GEMD58AQHadtw0IFGvHasu_vSJGKjUsdooULTPK-DZDfm9N3OI60IjU88HcXQWTDVOtMOV23ruWhW5DYIaiQDoBwLUbt9EpS9LC_MQnkVDYODQ6K9Lcz_9yJrBux5BYbG_rBEWI9CCbe9CI-8P1RQpUq_aPBfCjVyrBujn2rueqnJu97CPRchpLei6ZQ88JSU0X3Kl8PTPDE8ncMwpL5UMAyAP4Ph7b6EblmPbJkr-W_dfb5u4VEnUkMfmElBWObnQcmwbnlHPYuCrLYiDAu0Ln2NvY1tpkU3R9z9x5pnZTZE4CAa214daTdV5BtoisiTNgAOIEcpJru6GB6gOUfUfYaWpYWpS3G3pMM3jWw-PJI1QCVdQ9KxskwqZMAWk3qx0Z2DHGz2K9pmUZiNHqtiIkxv1EtRXlY79Y4Bi38J0xNcZlFny8jeQoTPSSHk43d55eg-puBmXWvviF0JOKJdkTLhfLCrTWyfFLN2-gUePdnlzoXTLqrOPDozfdNGFSIXIq4cVEQXepsrzgq3-PFF5s2yqoxDpsbcPC_W3pfWhlJco_apBeFUb-hq0HVyT4XSxfAkE4eHuMaXiDadf1MBgpCApvMRAwFtA4PaPsGbdZ8z00vPkv2Y-Na5_z8f56tomTR-bzbK3sFriMHG3I-GYWwYdty71yZQNU
    lastmodified: "2026-06-19T12:04:49Z"
    mac: ENC[AES256_GCM,data:WaN2RZiFQCazh3piNSGW0k/bKRZmePn1wFr+icSTc6hUDn0KQdMLvNIkvingH19YqFb/E+HDkQex+nZwR7XvcXohKogiHGvkfieVU9FVxLAr5O6+K8AqsC/A56JA3DxAk+aPdNdsrP0+URMQf54iryo9LwfQ1SLKgjnBvqIB5qU=,iv:ttj2bddGx0SEdBx09QQ2fiU++RdUlQekeQ/6ARAzN1I=,tag:CCfG9jM8BdURN/pYA+xC2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2

---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: uyuni-prod-creds
    namespace: uyuni-operator-system
spec:
    secretTemplates:
        - name: uyuni-prod-creds
          type: Opaque
          stringData:
            username: ENC[AES256_GCM,data:lXQ1hC4=,iv:7mrY11e5oRRH7JpvcNQk2HA4v/Af9aNcjgZYRVUKvaQ=,tag:0YvBQwMe55Da3x8N5Kw3RQ==,type:str]
            password: ENC[AES256_GCM,data:w9zJNG15eCigkmGSMAYBi/MCUMqN6w==,iv:9NbyXILL2h8McA2cg+6Uo1FoDxnYcLcZHaR9ZxRSQzM=,tag:IKhquJLTPHeP+2NkyKYlwQ==,type:str]
sops:
    azure_kv:
        - vault_url: https://kv-becse-ngpdwe0150.vault.azure.net
          name: sops-key
          version: b9f8c5318f69463d9dece1f310af530b
          created_at: "2026-06-19T11:54:08Z"
          enc: DoyqXJKz7BL-aMhDNmb8aB_539OkmS7ylRSVeJgIlwTM2d3EbsHEZ6n1tpwB2IYUdF2xEkaVWhk98G9Roaf97lDUtxH-lDqCGQFOm9qN-UMgbRzCvvYebGoGSRqTTY6nY3e2mnv2GZi9kaxEWHxikXf0Taw2TsbwpanYkka7TiQQH-cnU6SUKa9w7-_BECHzz42xcip3AjNtEg0vZuZgnlgg1Z0DtYLWjrNcjuZr4AFpFikcVkIgkNpR17LI_2IwQd_PU-gCuF6LXJp49C3Svh9OeE_2qHGTvFwcb9TFKgmR8FWvC6CHtVaYU8P2T9-2xyROefkEF8LHdwr-dVylyHR9xTIhoQZK78bmtfOO687rckFuR9LP0wik0yf6pXhvyvs-uG9uY1oEJzc0VsdmWV2gREJNAFFvGfnv41c4Ramd1AJ4_jMNuX6mYN2ebWHF5tZGvBK-If4srFY1Tr2xutw3Qn8HoFQItEJeqyWlEYeCDxRogz2KDMqtAHrA2D1qgNv5Hwl4rtSHjcsi-IVDepc53dNta8b02qBudX69jFMSCgtv0bpdyR8IpdA3-LrZpRNwzNWv1MdCquxML1XecCo4BzDxXcrk9ZQwk84OfH6Z6i2wiqGRwzqv8ExkCN0cT9aGD0MwBe2wk9cTFV84PTAFaRQU8ZcvfoJetaBmAv4
    lastmodified: "2026-06-19T11:54:10Z"
    mac: ENC[AES256_GCM,data:29WqA58BOgK/tnKI+gOs0dMfYDZ2wCQtr4BJDajjm+6m25Xm2gqzLFvQI1URaIemV896qTJSwE4Ew+qIRkuMntk0RQy3M4+lOzA+s+ILi06IDW3cpvhrppmV7KjLnSGiLNuA/bYX+VdXGPzg85vPpeki8sBjSFtQHFcyp3xDa2Q=,iv:+Pt1EfLwS0IO9epVCMeDyW+TSwc0AWQuTXP7Yapm+hM=,tag:PQVPC/1JPPrzeBnwbOV6KQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
