apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dockerhub-secret
    namespace: uyuni-operator-system
spec:
    secretTemplates:
        - name: dockerhub-secret
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:yYUU2MiZ2tN9/wIQT0F5zX3OnvokqWEAzQbX0xDXbeT/o4dh98b+UTdPYrTFxs6pdSAjPs1/ZUkVaAHxJM618E83+peiBWox0F1IU9fAT8/W7+VMS/UBshAoAvSW3JQdEGIYzPLsFNBoaY462J1qtPi2cVA6oDWhbqhAC7+qybYTRIWRN/xywzFygDSiC62Z3SCJLRCi5W+HeHQW0o4HG6QwT6pvDxAvEOm0lVPEv/7uHO/yBmtzd2Ybn+P8Yz0A8Z0C7ZJ2s/J3PXGkLYIFtGAmGemlZCC3zrJnhH1zB6OnFQTaR35dtuj1EKowZ1wJITV/BEBfYmxtauJ8MuDfKQ==,iv:0V4Z6IF+TJLZHYIMBjk9BNImtmFFpk05qqbzZ4+AuGc=,tag:jtLw/5vLQ6YwcHns1xy0nw==,type:str]
sops:
    azure_kv:
        - vault_url: https://kv-becse-ngpdwe0150.vault.azure.net
          name: sops-key
          version: b9f8c5318f69463d9dece1f310af530b
          created_at: "2026-06-19T11:53:33Z"
          enc: O3_CNQZQI7br80En2r6WX-ptqkQYGYaADENONV9rf9F26D-1ifgTtHdygvGgbQ_rNabNfPny30oMGB__EyxNMG4x6bBcSpyIe2pr8EaeXP6fSzSD1mlhpxXLu9bHerVGTXLA9QyYplhkeVX-Ua8Fdm9pjJR5e4J4jRj1x8lEQ9Vj9hjWFuMbo03HfuWWx9magd8m-KvylajzsW4RYSfqlNAyW5hzzFazIMwlfxHNvm7ZA_Zx1IX_h5SmzW-VFlmi2g6Ejm2zdaOpbJJ_GN7POMtQ0RywcUvTAouHRW8pivgp6YP8SYElQOfIztWbx3aHnUOKrNWUI1CI75-kqwjTs-17y4u-jR0KX_fO5_n8Zf0qS4kBa2To9RgAd1Z7aBY8iT4fazUZXJDc7HlgY1yvSTa49TbtUjoXnUbU9D-eBBx7K2LfBTCuqbb2GhkbTjb4O9fN9Me1dbzdqqbI72YE2AfqAYElzVUhwtxS30FVpzheo7B_CVvQlhkskUT7E8GBJJm-nyYtIEHv0xt2Oc8A9odd-OkGRK3B6EgKWnkYYkPkxxbgAZza6wzX1Elc9tIATnOon42Dgylg2p_cG_suVtvXDLG_DIsUprvkWWQwfQayYFD5PfmVJZ_aWzhdusBIpVDsmWOgw3ZaKBuxZAiqsTQRNTpcz6WJPRcRVndSXs8
    lastmodified: "2026-06-19T11:53:37Z"
    mac: ENC[AES256_GCM,data:sN5mmq0EpNTI4wpEAayX9FQL73FRRQsXN54BhVuEzFZ2ojfWO/nP9mcluRA1NpJsQcN2YXt3k7nA3JpNa3F54w+Y6mzgjr3efzmgj4sY/lzf2XUJC+yMGIA+GFLfqPq+m0RD1Z1IVChyDX03E8ByRKC7AFOosrsNJ6rKTOXgjR0=,iv:xjNq5VmqJwIpteFne80FezlbmU2htvRK8wgBEvUPxXw=,tag:ViVwPX86JK5Gv1mmd/fTkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2

---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: uyuni-prod-creds
    namespace: uyuni-operator-system
spec:
    secretTemplates:
        - name: uyuni-prod-creds
          type: Opaque
          stringData:
            username: ENC[AES256_GCM,data:lXQ1hC4=,iv:7mrY11e5oRRH7JpvcNQk2HA4v/Af9aNcjgZYRVUKvaQ=,tag:0YvBQwMe55Da3x8N5Kw3RQ==,type:str]
            password: ENC[AES256_GCM,data:w9zJNG15eCigkmGSMAYBi/MCUMqN6w==,iv:9NbyXILL2h8McA2cg+6Uo1FoDxnYcLcZHaR9ZxRSQzM=,tag:IKhquJLTPHeP+2NkyKYlwQ==,type:str]
sops:
    azure_kv:
        - vault_url: https://kv-becse-ngpdwe0150.vault.azure.net
          name: sops-key
          version: b9f8c5318f69463d9dece1f310af530b
          created_at: "2026-06-19T11:54:08Z"
          enc: DoyqXJKz7BL-aMhDNmb8aB_539OkmS7ylRSVeJgIlwTM2d3EbsHEZ6n1tpwB2IYUdF2xEkaVWhk98G9Roaf97lDUtxH-lDqCGQFOm9qN-UMgbRzCvvYebGoGSRqTTY6nY3e2mnv2GZi9kaxEWHxikXf0Taw2TsbwpanYkka7TiQQH-cnU6SUKa9w7-_BECHzz42xcip3AjNtEg0vZuZgnlgg1Z0DtYLWjrNcjuZr4AFpFikcVkIgkNpR17LI_2IwQd_PU-gCuF6LXJp49C3Svh9OeE_2qHGTvFwcb9TFKgmR8FWvC6CHtVaYU8P2T9-2xyROefkEF8LHdwr-dVylyHR9xTIhoQZK78bmtfOO687rckFuR9LP0wik0yf6pXhvyvs-uG9uY1oEJzc0VsdmWV2gREJNAFFvGfnv41c4Ramd1AJ4_jMNuX6mYN2ebWHF5tZGvBK-If4srFY1Tr2xutw3Qn8HoFQItEJeqyWlEYeCDxRogz2KDMqtAHrA2D1qgNv5Hwl4rtSHjcsi-IVDepc53dNta8b02qBudX69jFMSCgtv0bpdyR8IpdA3-LrZpRNwzNWv1MdCquxML1XecCo4BzDxXcrk9ZQwk84OfH6Z6i2wiqGRwzqv8ExkCN0cT9aGD0MwBe2wk9cTFV84PTAFaRQU8ZcvfoJetaBmAv4
    lastmodified: "2026-06-19T11:54:10Z"
    mac: ENC[AES256_GCM,data:29WqA58BOgK/tnKI+gOs0dMfYDZ2wCQtr4BJDajjm+6m25Xm2gqzLFvQI1URaIemV896qTJSwE4Ew+qIRkuMntk0RQy3M4+lOzA+s+ILi06IDW3cpvhrppmV7KjLnSGiLNuA/bYX+VdXGPzg85vPpeki8sBjSFtQHFcyp3xDa2Q=,iv:+Pt1EfLwS0IO9epVCMeDyW+TSwc0AWQuTXP7Yapm+hM=,tag:PQVPC/1JPPrzeBnwbOV6KQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
