---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - uyuni.uyuni-project.org
  resources:
  - activationkeys
  - autoinstalldistributions
  - clmenvironments
  - configurationchannels
  - contentprojects
  - custominfokeys
  - organizations
  - repositories
  - softwarechannels
  - systemgroups
  - systems
  - uyuniproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - uyuni.uyuni-project.org
  resources:
  - activationkeys/finalizers
  - autoinstalldistributions/finalizers
  - clmenvironments/finalizers
  - configurationchannels/finalizers
  - contentprojects/finalizers
  - custominfokeys/finalizers
  - organizations/finalizers
  - repositories/finalizers
  - softwarechannels/finalizers
  - systemgroups/finalizers
  - systems/finalizers
  - tasks/finalizers
  verbs:
  - update
- apiGroups:
  - uyuni.uyuni-project.org
  resources:
  - activationkeys/status
  - autoinstalldistributions/status
  - clmenvironments/status
  - configurationchannels/status
  - contentprojectpromotions/status
  - contentprojects/status
  - custominfokeys/status
  - organizations/status
  - repositories/status
  - softwarechannels/status
  - systemgroups/status
  - systems/status
  - tasks/status
  - uyuniproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - uyuni.uyuni-project.org
  resources:
  - autoinstallprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - uyuni.uyuni-project.org
  resources:
  - contentprojectpromotions
  - tasks
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
