apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linux-platform

resources:
# Only applying brandregionclam-apac.yaml for automatic deployment
# Other samples can be applied manually as needed
- brandregionclaim-apac.yaml
