apiVersion: v2
name: uyuni-operator
description: Kubernetes operator for declarative management of Uyuni server contents
type: application
version: 0.1.0
appVersion: "dev"
keywords:
  - uyuni
  - operator
  - gitops
home: https://github.com/mborodin/uyuni-operator
sources:
  - https://github.com/mborodin/uyuni-operator
maintainers:
  - name: uyuni-operator maintainers
kubeVersion: ">=1.27.0-0"
annotations:
  artifacthub.io/category: integration-delivery
